### ISSUE TITLE
Glottocodes for Sardinian appear to be wrong

### ISSUE THREAD

**Issue by davidainman** [lexibank/iecor#61]
The current CLLD gives the glottocode of Sardinian: Nuoro as lugo1236 and Sardinian: Lugudoro as nuor1238. I believe these should be reversed.

**Comment by cormacanderson** [comment]
Thanks for drawing this to our attention. We have looked into this and will give correct Glottocodes in the next version.

**Comment by Bibiko** [comment]
fixed with version 1.1 https://github.com/lexibank/iecor/releases/tag/v1.1
